### PR TITLE
Fix for the bug in the defaultbutton animation and several icons additions

### PR DESCRIPTION
**Pull request by BertrandDekoninck**
Hi, Alessandro !
A user (Johannes Brakensiek johannes@luki.org) kindly offers us a simple fix for the bug I talked you about several months ago. 
It looks sensible. I integrated it in my branch and everything seems to be OK.
I also push some updates I did on my icons and I reverted the menuBar height to 24.

### CODE REVIEW

**Comment by AlessandroSangiuliano** [comment]
Hi Bertrand,

You write at the right time, because I restarted some days ago to code in Objective-C.

I had and I still have problems rebooting gnustep on my old main system, it was an ubuntu updated an re updated on the years, so with the last release of ubuntu with the adoption of Gnome 3 some library seems broken for gnustep and I still didnt fidn which one is...

The good news is that i done a fresh install of arch on my laptop and I installed (almost) eithout problems GNUstep  there, also I installed an old version of mac os x 10.7 on my old macbook. After that I configured libxcb and xcode to link to libxcb and I started to write XCBKit.

A Kit (sdk) that should help the implementation of a modern window manager in objective-c using libxcb.

XCB is better than XLib, is modern and async. The work id also sustained by the David's code; he wrote time ago another XCBKit but it was an Etoile component while I want something of indipendent. His cose is really good and a good study/starting point for the implementation. Also, a lot of the code of my XCBKit is similar or equal to his code, I can see is a reimplementation and not a rework. My goal also is to make the code readable by everyones, the David's one has some nice and elegant tricks but make the code readable for people that have a good/high C Knowledge. (Honestly I'd like to keep the code of that tricks has he wrote, but is better for convenience to make it more simple)

Tomorrow I'll give a better look to the fix  for the animation button, I just looked and it seems to make sense, so porbably i'll merge it.

Thank you,
Alex.



________________________________
Da: Bertrand Dekoninck <notifications@github.com>
Inviato: mercoledì 1 maggio 2019 15:19
A: AlessandroSangiuliano/rik.theme
Cc: Subscribed
Oggetto: [AlessandroSangiuliano/rik.theme] Fix for the bug in the defaultbutton animation and several icons additions (#13)


Hi, Alessandro !
A user (Johannes Brakensiek johannes@luki.org<mailto:johannes@luki.org>) kindly offers us a simple fix for the bug I talked you about several months ago.
It looks sensible. I integrated it in my branch and everything seems to be OK.
I also push some updates I did on my icons and I reverted the menuBar height to 24.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/AlessandroSangiuliano/rik.theme/pull/13

Commit Summary

  *   Add new FileIcon for Cynthiune, redone the appicon of Cynthiune
  *   Update FileManager icon into a flashier one
  *   Refresh Cynthiune icon and document icon, brighter
  *   New custom AClock icon
  *   Menubar height : 26 px ; add newscreen.png
  *   Menubar height : 24 px ; add newscreen.png
  *   Merge branch 'master' of https://github.com/BertrandDekoninck/rik.theme
  *   Added missing FileIcon_xz.tiff in Zipper
  *   Fix for BertrandDekoninck/rik.theme#1
  *   Merge branch 'Letterus-master' from Johannes Brakensiek. It fixes a bug in the defaultbutton animation (not stopping when releasing a window).

File Changes

  *   M NSWindow+Rik.m<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-0> (13)
  *   M Resources/ThemeImages/org.gap.AClock/AClock.tiff<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-1> (0)
  *   A Resources/ThemeImages/org.gap.Cynthiune/Cynthiune-song-48.tiff<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-2> (0)
  *   A Resources/ThemeImages/org.gap.Cynthiune/Cynthiune.tiff<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-3> (0)
  *   A Resources/ThemeImages/org.gap.Zipper/FileIcon_xz.tiff<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-4> (0)
  *   M Resources/ThemeImages/org.gnustep.GWorkspace/FileManager.tiff<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-5> (0)
  *   M Rik+Menu.m<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-6> (2)
  *   A newscreen.png<https://github.com/AlessandroSangiuliano/rik.theme/pull/13/files#diff-7> (0)

Patch Links:

  *   https://github.com/AlessandroSangiuliano/rik.theme/pull/13.patch
  *   https://github.com/AlessandroSangiuliano/rik.theme/pull/13.diff

**Comment by BertrandDekoninck** [comment]
I had first replied with my mailer, but I'm afraid that the mail address given by github was a "noreply" one. So I do this again now and updated the end of the mail.
Le 01/05/2019 à 23:31, Alessandro Sangiuliano a écrit :

> Hi Bertrand,

> You write at the right time, because I restarted some days ago to code in 
> Objective-C.

> I had and I still have problems rebooting gnustep on my old main system, it 
> was an ubuntu updated an re updated on the years, so with the last release of 
> ubuntu with the adoption of Gnome 3 some library seems broken for gnustep and 
> I still didnt fidn which one is...

I don't use GNUstep with Gnome nor Mate because it conflicts with gnustep global menu. I always use it with Windowmaker and I am quite happy with my desktop.

> The good news is that i done a fresh install of arch on my laptop and I 
> installed (almost) eithout problems GNUstep there, also I installed an old 
> version of mac os x 10.7 on my old macbook. After that I configured libxcb 
> and xcode to link to libxcb and I started to write XCBKit.

> A Kit (sdk) that should help the implementation of a modern window manager in 
> objective-c using libxcb.

> XCB is better than XLib, is modern and async. The work id also sustained by 
> the David's code; he wrote time ago another XCBKit but it was an Etoile 
> component while I want something of indipendent. His cose is really good and 
> a good study/starting point for the implementation. Also, a lot of the code 
> of my XCBKit is similar or equal to his code, I can see is a reimplementation 
> and not a rework. My goal also is to make the code readable by everyones, the 
> David's one has some nice and elegant tricks but make the code readable for 
> people that have a good/high C Knowledge. (Honestly I'd like to keep the code 
> of that tricks has he wrote, but is better for convenience to make it more 
> simple)
So you still want to build a window manager ? That's a pretty big picture... More of the etoile project should be made independant.


> Tomorrow I'll give a better look to the fix for the animation button, I just 
> looked and it seems to make sense, so porbably i'll merge it.


Great. Johannes told me moreover that there may still be some memory problems to take care of. I'm not the best to track this.

For now, I'm trying to build rik with gcc and its objc runtime  : I want to have a more recent rik on powerpc linux too and libobjc2 is still not an option. 
I succeeded by disabling the defaultButton animation code, that has an extended use of objc_getAssociatedObject, which isn't available in the gcc runtime. 
Maybe we could discuss later of a way to replace this by something working with gcc, in order to have the same code of rik available on all platforms.
 I also had to declare a category for the use of a private method of GSTheme. This latter patch fixes a warning that also causes an error with gcc, but not with clang. There are several warning left, that we should take care of.  This can go in rik.theme head. I'll do a PR later.

**Comment by AlessandroSangiuliano** [comment]
I just read the 2 messages. My response and your reply... I'll never write anymore from Mac with mail in english, its autocorrection makes my english more bad than it really is...

I merged the pull request, for now it makes sense, for other memory problems I should test the theme on OS X, or at least wait for some vacation, due of few time.

I use my few time in the weekends to develop the XCBKit. I really want a window manager written in ObjC that can be easily integrated with GNUstep and able to handle all kinds of windows (GNUstep and non-).

I saw Greg started a project; something called "Dock base GNUstep application". I didn't understand what he meant, maybe a Dock app? Would be nice! Otherwise I had that in my TODO list.

Sooner or later I'll put the code XCBKit code implemented until now here on github, I hope someone will help.

It was quite easy configuring X11 on OS 10.7 and the relatives libs to write the code with XCode. I should ask to someone what is the status of GNUstep compatibility with 10.8, so I can use some updated browsers.

**Comment by AlessandroSangiuliano** [comment]
PPC Replay:

Unfortunately I haven't a PPC hardware so I can't test it. Well I have a PS3 but I should do a lot of work to get a linux on that hardware after they put off the option to install another operating system on the PS3.

**Comment by BertrandDekoninck** [comment]
I manage to build rik on ppc, but I disabled the animation code. Maybe we could just use ifdef conditions to merge the two versions in one that could be build on any platform. I've never done this yet.
I've also submitted a new PR a few minutes ago to use NSUserDefaults to adlust the menubar transparency.

**Comment by armm77** [comment]
hello @AlessandroSangiuliano  maybe this helps something. I uploaded it to my git but I have not had time to review it.

http://interfacewm.sourceforge.net/

**Pull request merged**
