### PR TITLE
Update with latest RikIcons :

### PR DESCRIPTION
**Pull request by BertrandDekoninck**
- update Music folder
- new common_linkCursor
- new search folder icons for Live seraches and MDFinder
- update  transitionnal common_ProgressIndeterminate icons

### CODE REVIEW

**Comment by BertrandDekoninck** [comment]
Sorry, I've included by accident in the pull request an org.GNUstep.Workspace.Gnumeric folder which was an attempt to theme an app wrapper. It works but it's work in progress and I need to talk with Riccardo M. first about the CFBundleIdentifier I choose for this. This should be removed from the commit.

**Comment by AlessandroSangiuliano** [comment]
Hello Bertrand.

The commit says that you are Deleting some images with this commit, look here:

https://github.com/AlessandroSangiuliano/rik.theme/pull/7/files

You are deleting:

Resources/ThemeImages/org.gnustep.GWorkspace.LiveSearchFolder/LiveSearchFolder.png

and:

Resources/ThemeImages/org.gnustep.GWorkspace.LiveSearchFolder/LiveSearchFolder.tiff

It is correct that you want to delete that files? 

Also you are adding a file:

Resources/ThemeImages/org.gnustep.GWorkspace.gnumeric.wrapper/.gwdir

Do you really want to add this file, or is just an error?

Look also at the .gitignore file that adds 2 new entries:

.AppleDouble that I don't know what is, and the previous file .gwdir.

I wait your answer before commit.

However to see what is in the (your) LOCAL and REMOTE repo, you should use:

git status

It will show what is modified and what you need to add to sync LOCAL and REMOTE with:

git add <a_file_or_directory>

**Comment by AlessandroSangiuliano** [comment]
I forget to say that the 2 files you are deleting are not present in my repo, so I'm going to think something gone wrong with your commit, but I wait :)

**Comment by AlessandroSangiuliano** [comment]
The .gwdir file should not be included in the commit. What is the .AppleDouble?

**Comment by BertrandDekoninck** [comment]
Le 16/03/2016 08:24, Alessandro Sangiuliano a écrit :
> Hello Bertrand.
>
> The commit says that you are Deleting some images with this commit, look
> here:
>
> https://github.com/AlessandroSangiuliano/rik.theme/pull/7/files
>
> You are deleting:
>
> Resources/ThemeImages/org.gnustep.GWorkspace.LiveSearchFolder/LiveSearchFolder.png
>
> and:
>
> Resources/ThemeImages/org.gnustep.GWorkspace.LiveSearchFolder/LiveSearchFolder.tiff
>

Deleted but I've added the tiff version only in org.GNUstep.GWorkspace, 
see at the bottom of the list of files.
I've suppressed the org.gnustep.GWorkspace.LiveSearchFolder because it 
was a not needed CFBundleIdentifier for LiveSearchFolder icon.


> It is correct that you want to delete that files?
>
> Also you are adding a file:
>
> Resources/ThemeImages/org.gnustep.GWorkspace.gnumeric.wrapper/.gwdir
>
> Do you really want to add this file, or is just an error?

I left a comment yesterday evening bout this. The whole 
Resources/ThemeImages/org.gnustep.GWorkspace.gnumeric.wrapper should not 
be included in the merge. It was a working attempt to theme the an 
app_wrapper icon. But I need now to ask Riccardo for a naming rule of 
the CFBundleIdentifier (the org.GNUstep... thing which is included in 
the application plist). So it can be deleted here.

>
> Look also at the .gitignore file that adds 2 new entries:
>
> .AppleDouble that I don't know what is, and the previous file .gwdir.

.AppleDouble are created by linux netatalk or osX appletalk fileserver. 
They are present in all my folders.

They appear in red on each of my "git status" (of course I do that) and 
I don't want to deal with them at each time. So I added it to my 
personnal .gitignore.

Same for .gwdir : it's the way Gworkspace stores folders viewing 
preferences (position, type of view)... it's created by GWorkspace each 
you change a viewing setting on a folder (listView to IconView and so 
on). They are present in all my folders.

Cheers, Bertrand

**Comment by BertrandDekoninck** [comment]
Le 16/03/2016 08:26, Alessandro Sangiuliano a écrit :
> I forget to say that the 2 files you are deleting are not present in my
> repo, so I'm going to think something gone wrong with your commit, but I
> wait :)

Which ones ? The two LiveSearchFolder icons ? I see them here :

https://github.com/AlessandroSangiuliano/rik.theme/tree/master/Resources/ThemeImages/org.gnustep.GWorkspace.LiveSearchFolder

Bertrand

**Comment by BertrandDekoninck** [comment]
Le 16/03/2016 08:34, Alessandro Sangiuliano a écrit :
> The .gwdir file should not be included in the commit. What is the
> .AppleDouble?
>
Of wourse, that's why I added the .gitignore rule.
Bertrand

**Comment by BertrandDekoninck** [comment]
> It will show what is modified and what you need to add to sync LOCAL and
> REMOTE with:
>
> git add

I forgot to say : I usually pull the remote repo of rik (yours), then I 
check the status, add,  commit and push to my own remote repo.

That's what I've done before the merge request. There shouldn't be 
problems this way. The only thing I forgot was this gnumeric folder that 
I had'nt deleted first.

Sorry.

Bertrand.

**Comment by AlessandroSangiuliano** [comment]
Ok fully understood the changes, thank you. now I can merge the request

**Comment by BertrandDekoninck** [comment]
Le 16/03/2016 10:42, Alessandro Sangiuliano a écrit :
> Merged #7 <https://github.com/AlessandroSangiuliano/rik.theme/pull/7>.
>
I just made another pull request though : I forgot, to rename 
common_MovieFolder to common_VideoFolder (needed by latest base/gui to 
display a videofolder icon).

Bertrand

**Pull request merged**
